Bump ``mypy`` to ``v0.991`` and fix lint errors
